"""HTTP transport and content helpers."""

from __future__ import annotations

import time

from .body import (
    DEFAULT_MAX_COMPRESSED_BODY_MULTIPLIER,
    DEFAULT_MAX_RESPONSE_BYTES,
    TEXTUAL_CONTENT_TYPES,
    build_text_preview,
    decompress_gzip_body,
    is_textual_content_type,
    is_xml_content_type,
    normalize_content_encoding,
)
from .cache import (
    CACHE_KEY_HEADER_NAMES,
    DEFAULT_CACHE_CAPACITY,
    DEFAULT_CACHE_TTL_SECONDS,
    DEFAULT_MAX_CACHEABLE_BODY_BYTES,
    DEFAULT_MAX_TOTAL_CACHE_BYTES,
    REDACTED_CACHE_HEADER_DIGEST_PREFIX,
    REDACTED_CACHE_VALUE,
    SENSITIVE_CACHE_HEADER_NAMES,
    SENSITIVE_QUERY_PARAM_NAMES,
    UNSTABLE_CACHE_HEADER_NAMES,
    _CacheKey,
    diagnostic_url_payload,
    is_sensitive_query_param_name,
    redact_text_for_diagnostics,
    redact_url_for_cache,
    redact_url_for_diagnostics,
)
from .content_types import (
    PDF_ACCEPT_HEADER,
    PDF_MIME_TYPE,
    STRUCTURED_TEXT_MIME_TYPES,
    content_type_base,
    is_pdf_content_type,
)
from .errors import (
    RequestCancelledError,
    RequestErrorCategory,
    RequestFailure,
    build_http_error_message,
    build_network_error_detail,
    classify_network_error,
    is_retryable_network_error,
    is_timeout_network_error,
    iter_network_error_causes,
)
from .json_payload import decode_json_object_response
from .retry import (
    DEFAULT_TRANSIENT_BACKOFF_BASE_SECONDS,
    DEFAULT_TRANSIENT_RETRIES,
    TRANSIENT_HTTP_STATUS_CODES,
    is_transient_http_status,
    parse_retry_after_seconds,
)
from .transport import (
    DEFAULT_FULLTEXT_TIMEOUT_SECONDS,
    DEFAULT_MAX_REDIRECTS,
    DEFAULT_PER_HOST_CONCURRENCY,
    DEFAULT_POOL_MAXSIZE,
    DEFAULT_POOL_NUM_POOLS,
    DEFAULT_TIMEOUT_SECONDS,
    HttpRequestPolicy,
    HttpStreamOptions,
    HttpTransport,
    HttpTransportOptions,
    _PreparedRequest,
    logger,
)
from .url_policy import (
    DEFAULT_REMOTE_PORTS,
    DEFAULT_SAFE_REMOTE_URL_POLICY,
    SafeRemoteUrlPolicy,
    ValidatedRemoteUrl,
)
from .provider_policy import provider_allowed_hosts, provider_request_policy

__all__ = [
    "CACHE_KEY_HEADER_NAMES",
    "DEFAULT_CACHE_CAPACITY",
    "DEFAULT_CACHE_TTL_SECONDS",
    "DEFAULT_FULLTEXT_TIMEOUT_SECONDS",
    "DEFAULT_MAX_CACHEABLE_BODY_BYTES",
    "DEFAULT_MAX_COMPRESSED_BODY_MULTIPLIER",
    "DEFAULT_MAX_REDIRECTS",
    "DEFAULT_MAX_RESPONSE_BYTES",
    "DEFAULT_MAX_TOTAL_CACHE_BYTES",
    "DEFAULT_PER_HOST_CONCURRENCY",
    "DEFAULT_POOL_MAXSIZE",
    "DEFAULT_POOL_NUM_POOLS",
    "DEFAULT_REMOTE_PORTS",
    "DEFAULT_SAFE_REMOTE_URL_POLICY",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_TRANSIENT_BACKOFF_BASE_SECONDS",
    "DEFAULT_TRANSIENT_RETRIES",
    "PDF_ACCEPT_HEADER",
    "PDF_MIME_TYPE",
    "REDACTED_CACHE_HEADER_DIGEST_PREFIX",
    "REDACTED_CACHE_VALUE",
    "SENSITIVE_CACHE_HEADER_NAMES",
    "SENSITIVE_QUERY_PARAM_NAMES",
    "STRUCTURED_TEXT_MIME_TYPES",
    "TEXTUAL_CONTENT_TYPES",
    "TRANSIENT_HTTP_STATUS_CODES",
    "UNSTABLE_CACHE_HEADER_NAMES",
    "HttpRequestPolicy",
    "HttpStreamOptions",
    "HttpTransport",
    "HttpTransportOptions",
    "RequestCancelledError",
    "RequestErrorCategory",
    "RequestFailure",
    "SafeRemoteUrlPolicy",
    "ValidatedRemoteUrl",
    "_CacheKey",
    "_DiskCacheEntry",
    "_PreparedRequest",
    "build_http_error_message",
    "build_network_error_detail",
    "build_text_preview",
    "classify_network_error",
    "content_type_base",
    "decode_json_object_response",
    "decompress_gzip_body",
    "diagnostic_url_payload",
    "is_pdf_content_type",
    "is_retryable_network_error",
    "is_sensitive_query_param_name",
    "is_textual_content_type",
    "is_timeout_network_error",
    "is_transient_http_status",
    "is_xml_content_type",
    "iter_network_error_causes",
    "logger",
    "normalize_content_encoding",
    "parse_retry_after_seconds",
    "provider_allowed_hosts",
    "provider_request_policy",
    "redact_text_for_diagnostics",
    "redact_url_for_cache",
    "redact_url_for_diagnostics",
    "time",
]
