"""Shared quality and HTML extraction reason-code constants."""

from __future__ import annotations

from ..reason_codes import (
    ABSTRACT_ONLY,
    ACCESS_PAGE_URL,
    AWS_WAF_CHALLENGE,
    BODY_SUFFICIENT,
    CITATION_ABSTRACT_HTML_URL,
    CLOUDFLARE_CHALLENGE,
    DATA_ARTICLE_ACCESS_ABSTRACT,
    DATA_ARTICLE_ACCESS_NO,
    EMPTY_ARTICLE_SHELL,
    FINAL_URL_MATCHES_CITATION_ABSTRACT_HTML_URL,
    FULLTEXT,
    INSUFFICIENT_BODY,
    METADATA_ONLY,
    NO_ACCESS,
    PUBLISHER_ACCESS_DENIED,
    PUBLISHER_NOT_FOUND,
    PUBLISHER_PAYWALL,
    REDIRECTED_TO_ABSTRACT,
    STRUCTURED_ARTICLE_NOT_FULLTEXT,
    STRUCTURED_MISSING_BODY_SECTIONS,
    WT_ABSTRACT_PAGE_TYPE,
)


__all__ = [
    "ABSTRACT_ONLY",
    "ACCESS_PAGE_URL",
    "AWS_WAF_CHALLENGE",
    "BODY_SUFFICIENT",
    "CITATION_ABSTRACT_HTML_URL",
    "CLOUDFLARE_CHALLENGE",
    "DATA_ARTICLE_ACCESS_ABSTRACT",
    "DATA_ARTICLE_ACCESS_NO",
    "EMPTY_ARTICLE_SHELL",
    "FINAL_URL_MATCHES_CITATION_ABSTRACT_HTML_URL",
    "FULLTEXT",
    "INSUFFICIENT_BODY",
    "METADATA_ONLY",
    "NO_ACCESS",
    "PUBLISHER_ACCESS_DENIED",
    "PUBLISHER_NOT_FOUND",
    "PUBLISHER_PAYWALL",
    "REDIRECTED_TO_ABSTRACT",
    "STRUCTURED_ARTICLE_NOT_FULLTEXT",
    "STRUCTURED_MISSING_BODY_SECTIONS",
    "WT_ABSTRACT_PAGE_TYPE",
]
